
package gui;

// Importando bibliotecas
import database.Banco;
import java.sql.*;
import javax.swing.JOptionPane;

public class frm_forma_pagamento extends javax.swing.JFrame {
    
    // Instancia da classe de Conexão
    Banco banco;
    
    // Variável Código Cliente
    int codigo_cliente = 0;
    
    // Variável descontos
    int desconto = 0;
    
    // Select principal
    String sql = "select * from cliente";

    // Construtor
    public frm_forma_pagamento(double valor_compra, int quantidade_pontos_desconto, int codigo_cli) {
        initComponents();
        
        // Criando objeto da classe Banco
        banco = new Banco();

        // Abrir conexão com o banco de dados
        banco.connect();  
        
        // Carregar dados
        banco.executeSQL(sql);
        
        try {
            // Procura o primeiro registro no banco
            banco.resultset.first();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao acessar dados\n" + e, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        
        // Receber descontos
        this.desconto = quantidade_pontos_desconto;
        
        // Receber o código do cliente
        this.codigo_cliente = codigo_cli;
        
        // Mostrar os valores de compra e desconto
        lbl_valor_compra.setText("Valor da Compra: R$ " + valor_compra);
        lbl_desconto.setText("" + desconto);
               
    }
    
    // Método voltar_menu - volta ao menu principal
    public void voltar_menu(){
        // Esse botão volta ao form Principal
        new frm_principal().setVisible(true);
        this.dispose();
        
        // Fechar a conexão com o banco
        banco.disconnect();
    }
    
    // Método adicionar_pontos_desconto - adiciona a quantidade de pontos da compra ao perfil do cliente
    public void adicionar_pontos_desconto() {
        try{
            //Comando SQL
            String comando = "update cliente set ponto_cli = " + desconto + " where codigo_cli = " + codigo_cliente;
            
            // Executar comando SQL
            banco.statement.executeUpdate(comando);
            
        // Se algo der errado, mostrar mensagem
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao alterar pontos do cliente!\n" + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_desconto1 = new javax.swing.JLabel();
        btn_finalizar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbl_valor_compra = new javax.swing.JLabel();
        lbl_desconto = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagamento");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_desconto1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lbl_desconto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_desconto1.setText("Você ganhou pontos!!");
        lbl_desconto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_desconto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 160, -1));

        btn_finalizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Template/botao4.png"))); // NOI18N
        btn_finalizar.setText("Finalizar");
        btn_finalizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Dinheiro", "2 - Cartão de Crédito", "3 - Cartão de Débito", "4 - Vale Alimentação" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 170, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Forma de Pagamento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lbl_valor_compra.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_valor_compra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_valor_compra.setText("Valor da Compra: R$ 00,00");
        lbl_valor_compra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_valor_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lbl_desconto.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lbl_desconto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_desconto.setText("Você ganhou XXX pontos com esta compra");
        lbl_desconto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_desconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 130, 260, -1));

        lbl_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Template/template4.png"))); // NOI18N
        getContentPane().add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 220));

        lbl_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Template/btn2.png"))); // NOI18N
        getContentPane().add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, 20));

        lbl_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Template/btn3.png"))); // NOI18N
        getContentPane().add(lbl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, 220, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        adicionar_pontos_desconto();
        
        // Mensagem de Confirmação
        JOptionPane.showMessageDialog(null, "Venda realizada com sucesso", "Vendas", JOptionPane.INFORMATION_MESSAGE);
        voltar_menu();
    }//GEN-LAST:event_btn_finalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_forma_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_forma_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_forma_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_forma_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_forma_pagamento(1,1,1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_desconto;
    private javax.swing.JLabel lbl_desconto1;
    private javax.swing.JLabel lbl_valor_compra;
    // End of variables declaration//GEN-END:variables
}
